### ISSUE TITLE
Transcode 'queue' is actually a 'stack' because I'm actually 'dumb'

### ISSUE THREAD

**Issue by lemonjesus** [lemonjesus/TranscodeBot#18]
for some reason, I had it in my head that `Array#pop` removed stuff from the front of an array. but that doesn't make sense, because `Array#push` puts it at the end, and `push` and `pop` are opposites. For it to be a queue, you enqueue with `Array#push` and dequeue with `Array#shift`.

**Comment by wesley5040** [comment]
I was just about to open an issue for this...
