### ISSUE TITLE
bot only processes file creations

### ISSUE THREAD

**Issue by mattmoon1123** [lemonjesus/TranscodeBot#4]
if files are moved into the input folder after being created elsewhere, the bot will not process them without some touching

**Comment by taylorz1** [comment]
Need to add a flag to the list of watched events.

https://www.rubydoc.info/github/nex3/rb-inotify/INotify/Notifier we're interested in "moved_to" 

On this line: https://github.com/lemonjesus/TranscodeBot/blob/638c51478805c3415df55c3b7232606eb78b6464/TranscodeBot.rb#L120

**Comment by lacraig2** [comment]
Why not just iterate over current files in the directory on startup and call the same method with it's name.

**Comment by mattmoon1123** [comment]
> Why not just iterate over current files in the directory on startup and call the same method with it's name.

that address issue #7 not this one

**Comment by lemonjesus** [comment]
fixed in version 2.1
