### ISSUE TITLE
ONLY 1 AUDIO TRACK IS PASSED THROUGH

### ISSUE THREAD

**Issue by mattmoon1123** [lemonjesus/TranscodeBot#5]
the bot will only pass through the 1st audio track in a file. this is a major issue that needs to be fixed as soon as possible and i have been complaining about this ever since the bot was created in the first place

**Comment by taylorz1** [comment]
https://video.stackexchange.com/questions/21734/ffmpeg-video-conversion-with-multiple-audio-tracks

**Comment by lemonjesus** [comment]
fixed in version 2.1
