### ISSUE TITLE
whatever this is

### ISSUE THREAD

**Issue by mattmoon1123** [lemonjesus/TranscodeBot#6]
#<Thread:0x000055d6867f72d8@TranscodeBot.rb:111 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.6.0/pathname.rb:43:in `match?': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/lib/ruby/2.6.0/pathname.rb:43:in `chop_basename'
        from /usr/local/lib/ruby/2.6.0/pathname.rb:101:in `cleanpath_aggressive'
        from /usr/local/lib/ruby/2.6.0/pathname.rb:89:in `cleanpath'
        from /usr/local/lib/ruby/2.6.0/pathname.rb:507:in `relative_path_from'
        from TranscodeBot.rb:68:in `process_file'
        from TranscodeBot.rb:114:in `block (2 levels) in <main>'
        from TranscodeBot.rb:112:in `loop'
        from TranscodeBot.rb:112:in `block in <main>'

**Comment by taylorz1** [comment]
Do you know the input that caused this error?

**Comment by mattmoon1123** [comment]
The error is caused by unicode characters in the filename. This does not necessarily have to be fixed, but it would be nice if it was

**Comment by lemonjesus** [comment]
I had this problem with a python program called `tvnamer` - it didn't like when episode titles in their input or output had non-ascii characters in their name and it would fail. I think I fixed it by setting the locale of my session to UTF-8. in this case, it'd be setting the local envs in the Docker container to UTF-8 and friends.

**Comment by lemonjesus** [comment]
fixed in version 2.1
